using Chinese.Core;
using System;

namespace Chinese.Numerics
{
    public static class Builtin
    {
        public static readonly IWord[] NumericalWords = new[]
        {
            new ChineseWord { Simplified = "壹", SimplifiedPinyin = "yi1", Traditional = "壹", TraditionalPinyin = "yi1", Tag = 1 },
            new ChineseWord { Simplified = "贰", SimplifiedPinyin = "er4", Traditional = "貳", TraditionalPinyin = "er4", Tag = 2 },
            new ChineseWord { Simplified = "叁", SimplifiedPinyin = "san1", Traditional = "叁", TraditionalPinyin = "san1", Tag = 3 },
            new ChineseWord { Simplified = "肆", SimplifiedPinyin = "si4", Traditional = "肆", TraditionalPinyin = "si4", Tag = 4 },
            new ChineseWord { Simplified = "伍", SimplifiedPinyin = "wu3", Traditional = "伍", TraditionalPinyin = "wu3", Tag = 5 },
            new ChineseWord { Simplified = "陆", SimplifiedPinyin = "lu4", Traditional = "陸", TraditionalPinyin = "lu4", Tag = 6 },
            new ChineseWord { Simplified = "柒", SimplifiedPinyin = "qi1", Traditional = "柒", TraditionalPinyin = "qi1", Tag = 7 },
            new ChineseWord { Simplified = "捌", SimplifiedPinyin = "ba1", Traditional = "捌", TraditionalPinyin = "ba1", Tag = 8 },
            new ChineseWord { Simplified = "玖", SimplifiedPinyin = "jiu3", Traditional = "玖", TraditionalPinyin = "jiu3", Tag = 9 },
            new ChineseWord { Simplified = "壹拾", SimplifiedPinyin = "yi1 shi2", Traditional = "壹拾", TraditionalPinyin = "yi1 shi2", Tag = 10 },
            new ChineseWord { Simplified = "贰拾", SimplifiedPinyin = "er4 shi2", Traditional = "貳拾", TraditionalPinyin = "er4 shi2", Tag = 20 },
            new ChineseWord { Simplified = "叁拾", SimplifiedPinyin = "san1 shi2", Traditional = "叁拾", TraditionalPinyin = "san1 shi2", Tag = 30 },
            new ChineseWord { Simplified = "肆拾", SimplifiedPinyin = "si4 shi2", Traditional = "肆拾", TraditionalPinyin = "si4 shi2", Tag = 40 },
            new ChineseWord { Simplified = "伍拾", SimplifiedPinyin = "wu3 shi2", Traditional = "伍拾", TraditionalPinyin = "wu3 shi2", Tag = 50 },
            new ChineseWord { Simplified = "陆拾", SimplifiedPinyin = "lu4 shi2", Traditional = "陸拾", TraditionalPinyin = "lu4 shi2", Tag = 60 },
            new ChineseWord { Simplified = "柒拾", SimplifiedPinyin = "qi1 shi2", Traditional = "柒拾", TraditionalPinyin = "qi1 shi2", Tag = 70 },
            new ChineseWord { Simplified = "捌拾", SimplifiedPinyin = "ba1 shi2", Traditional = "捌拾", TraditionalPinyin = "ba1 shi2", Tag = 80 },
            new ChineseWord { Simplified = "玖拾", SimplifiedPinyin = "jiu3 shi2", Traditional = "玖拾", TraditionalPinyin = "jiu3 shi2", Tag = 90 },
            new ChineseWord { Simplified = "壹佰", SimplifiedPinyin = "yi1 bai3", Traditional = "壹佰", TraditionalPinyin = "yi1 bai3", Tag = 100 },
            new ChineseWord { Simplified = "贰佰", SimplifiedPinyin = "er4 bai3", Traditional = "貳佰", TraditionalPinyin = "er4 bai3", Tag = 200 },
            new ChineseWord { Simplified = "叁佰", SimplifiedPinyin = "san1 bai3", Traditional = "叁佰", TraditionalPinyin = "san1 bai3", Tag = 300 },
            new ChineseWord { Simplified = "肆佰", SimplifiedPinyin = "si4 bai3", Traditional = "肆佰", TraditionalPinyin = "si4 bai3", Tag = 400 },
            new ChineseWord { Simplified = "伍佰", SimplifiedPinyin = "wu3 bai3", Traditional = "伍佰", TraditionalPinyin = "wu3 bai3", Tag = 500 },
            new ChineseWord { Simplified = "陆佰", SimplifiedPinyin = "lu4 bai3", Traditional = "陸佰", TraditionalPinyin = "lu4 bai3", Tag = 600 },
            new ChineseWord { Simplified = "柒佰", SimplifiedPinyin = "qi1 bai3", Traditional = "柒佰", TraditionalPinyin = "qi1 bai3", Tag = 700 },
            new ChineseWord { Simplified = "捌佰", SimplifiedPinyin = "ba1 bai3", Traditional = "捌佰", TraditionalPinyin = "ba1 bai3", Tag = 800 },
            new ChineseWord { Simplified = "玖佰", SimplifiedPinyin = "jiu3 bai3", Traditional = "玖佰", TraditionalPinyin = "jiu3 bai3", Tag = 900 },
            new ChineseWord { Simplified = "壹仟", SimplifiedPinyin = "yi1 qian1", Traditional = "壹仟", TraditionalPinyin = "yi1 qian1", Tag = 1000 },
            new ChineseWord { Simplified = "贰仟", SimplifiedPinyin = "er4 qian1", Traditional = "貳仟", TraditionalPinyin = "er4 qian1", Tag = 2000 },
            new ChineseWord { Simplified = "叁仟", SimplifiedPinyin = "san1 qian1", Traditional = "叁仟", TraditionalPinyin = "san1 qian1", Tag = 3000 },
            new ChineseWord { Simplified = "肆仟", SimplifiedPinyin = "si4 qian1", Traditional = "肆仟", TraditionalPinyin = "si4 qian1", Tag = 4000 },
            new ChineseWord { Simplified = "伍仟", SimplifiedPinyin = "wu3 qian1", Traditional = "伍仟", TraditionalPinyin = "wu3 qian1", Tag = 5000 },
            new ChineseWord { Simplified = "陆仟", SimplifiedPinyin = "lu4 qian1", Traditional = "陸仟", TraditionalPinyin = "lu4 qian1", Tag = 6000 },
            new ChineseWord { Simplified = "柒仟", SimplifiedPinyin = "qi1 qian1", Traditional = "柒仟", TraditionalPinyin = "qi1 qian1", Tag = 7000 },
            new ChineseWord { Simplified = "捌仟", SimplifiedPinyin = "ba1 qian1", Traditional = "捌仟", TraditionalPinyin = "ba1 qian1", Tag = 8000 },
            new ChineseWord { Simplified = "玖仟", SimplifiedPinyin = "jiu3 qian1", Traditional = "玖仟", TraditionalPinyin = "jiu3 qian1", Tag = 9000 },
            new ChineseWord { Simplified = "一", SimplifiedPinyin = "yi1", Traditional = "一", TraditionalPinyin = "yi1", Tag = 1 },
            new ChineseWord { Simplified = "二", SimplifiedPinyin = "er4", Traditional = "二", TraditionalPinyin = "er4", Tag = 2 },
            new ChineseWord { Simplified = "三", SimplifiedPinyin = "san1", Traditional = "三", TraditionalPinyin = "san1", Tag = 3 },
            new ChineseWord { Simplified = "四", SimplifiedPinyin = "si4", Traditional = "四", TraditionalPinyin = "si4", Tag = 4 },
            new ChineseWord { Simplified = "五", SimplifiedPinyin = "wu3", Traditional = "五", TraditionalPinyin = "wu3", Tag = 5 },
            new ChineseWord { Simplified = "六", SimplifiedPinyin = "liu4", Traditional = "六", TraditionalPinyin = "liu4", Tag = 6 },
            new ChineseWord { Simplified = "七", SimplifiedPinyin = "qi1", Traditional = "七", TraditionalPinyin = "qi1", Tag = 7 },
            new ChineseWord { Simplified = "八", SimplifiedPinyin = "ba1", Traditional = "八", TraditionalPinyin = "ba1", Tag = 8 },
            new ChineseWord { Simplified = "九", SimplifiedPinyin = "jiu3", Traditional = "九", TraditionalPinyin = "jiu3", Tag = 9 },
            new ChineseWord { Simplified = "一十", SimplifiedPinyin = "yi1 shi2", Traditional = "一十", TraditionalPinyin = "yi1 shi2", Tag = 10 },
            new ChineseWord { Simplified = "二十", SimplifiedPinyin = "er4 shi2", Traditional = "二十", TraditionalPinyin = "er4 shi2", Tag = 20 },
            new ChineseWord { Simplified = "三十", SimplifiedPinyin = "san1 shi2", Traditional = "三十", TraditionalPinyin = "san1 shi2", Tag = 30 },
            new ChineseWord { Simplified = "四十", SimplifiedPinyin = "si4 shi2", Traditional = "四十", TraditionalPinyin = "si4 shi2", Tag = 40 },
            new ChineseWord { Simplified = "五十", SimplifiedPinyin = "wu3 shi2", Traditional = "五十", TraditionalPinyin = "wu3 shi2", Tag = 50 },
            new ChineseWord { Simplified = "六十", SimplifiedPinyin = "liu4 shi2", Traditional = "六十", TraditionalPinyin = "liu4 shi2", Tag = 60 },
            new ChineseWord { Simplified = "七十", SimplifiedPinyin = "qi1 shi2", Traditional = "七十", TraditionalPinyin = "qi1 shi2", Tag = 70 },
            new ChineseWord { Simplified = "八十", SimplifiedPinyin = "ba1 shi2", Traditional = "八十", TraditionalPinyin = "ba1 shi2", Tag = 80 },
            new ChineseWord { Simplified = "九十", SimplifiedPinyin = "jiu3 shi2", Traditional = "九十", TraditionalPinyin = "jiu3 shi2", Tag = 90 },
            new ChineseWord { Simplified = "一百", SimplifiedPinyin = "yi1 bai3", Traditional = "一百", TraditionalPinyin = "yi1 bai3", Tag = 100 },
            new ChineseWord { Simplified = "二百", SimplifiedPinyin = "er4 bai3", Traditional = "二百", TraditionalPinyin = "er4 bai3", Tag = 200 },
            new ChineseWord { Simplified = "三百", SimplifiedPinyin = "san1 bai3", Traditional = "三百", TraditionalPinyin = "san1 bai3", Tag = 300 },
            new ChineseWord { Simplified = "四百", SimplifiedPinyin = "si4 bai3", Traditional = "四百", TraditionalPinyin = "si4 bai3", Tag = 400 },
            new ChineseWord { Simplified = "五百", SimplifiedPinyin = "wu3 bai3", Traditional = "五百", TraditionalPinyin = "wu3 bai3", Tag = 500 },
            new ChineseWord { Simplified = "六百", SimplifiedPinyin = "liu4 bai3", Traditional = "六百", TraditionalPinyin = "liu4 bai3", Tag = 600 },
            new ChineseWord { Simplified = "七百", SimplifiedPinyin = "qi1 bai3", Traditional = "七百", TraditionalPinyin = "qi1 bai3", Tag = 700 },
            new ChineseWord { Simplified = "八百", SimplifiedPinyin = "ba1 bai3", Traditional = "八百", TraditionalPinyin = "ba1 bai3", Tag = 800 },
            new ChineseWord { Simplified = "九百", SimplifiedPinyin = "jiu3 bai3", Traditional = "九百", TraditionalPinyin = "jiu3 bai3", Tag = 900 },
            new ChineseWord { Simplified = "一千", SimplifiedPinyin = "yi1 qian1", Traditional = "一千", TraditionalPinyin = "yi1 qian1", Tag = 1000 },
            new ChineseWord { Simplified = "二千", SimplifiedPinyin = "er4 qian1", Traditional = "二千", TraditionalPinyin = "er4 qian1", Tag = 2000 },
            new ChineseWord { Simplified = "三千", SimplifiedPinyin = "san1 qian1", Traditional = "三千", TraditionalPinyin = "san1 qian1", Tag = 3000 },
            new ChineseWord { Simplified = "四千", SimplifiedPinyin = "si4 qian1", Traditional = "四千", TraditionalPinyin = "si4 qian1", Tag = 4000 },
            new ChineseWord { Simplified = "五千", SimplifiedPinyin = "wu3 qian1", Traditional = "五千", TraditionalPinyin = "wu3 qian1", Tag = 5000 },
            new ChineseWord { Simplified = "六千", SimplifiedPinyin = "liu4 qian1", Traditional = "六千", TraditionalPinyin = "liu4 qian1", Tag = 6000 },
            new ChineseWord { Simplified = "七千", SimplifiedPinyin = "qi1 qian1", Traditional = "七千", TraditionalPinyin = "qi1 qian1", Tag = 7000 },
            new ChineseWord { Simplified = "八千", SimplifiedPinyin = "ba1 qian1", Traditional = "八千", TraditionalPinyin = "ba1 qian1", Tag = 8000 },
            new ChineseWord { Simplified = "九千", SimplifiedPinyin = "jiu3 qian1", Traditional = "九千", TraditionalPinyin = "jiu3 qian1", Tag = 9000 },
            new ChineseWord { Simplified = "两", SimplifiedPinyin = "liang3", Traditional = "两", TraditionalPinyin = "liang3", Tag = 2 },
            new ChineseWord { Simplified = "两百", SimplifiedPinyin = "liang3 bai3", Traditional = "两百", TraditionalPinyin = "liang3 bai3", Tag = 200 },
            new ChineseWord { Simplified = "两千", SimplifiedPinyin = "liang3 qian1", Traditional = "两千", TraditionalPinyin = "liang3 qian1", Tag = 2000 },

        };
    }
}
