// <auto-generated />
using System;
using Chinese.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbCreator.MySql.Migrations;

[DbContext(typeof(ChineseDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Chinese.Data.Char", b =>
            {
                b.Property<int>("Unicode")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Character")
                    .IsRequired()
                    .HasColumnType("varchar(1)");

                b.Property<string>("DefaultPinyin")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<bool>("IsPolyphone")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Pinyins")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<bool>("Sight")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Simplified")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<string>("Traditional")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<int>("Types")
                    .HasColumnType("int");

                b.HasKey("Unicode");

                b.ToTable("Chars");
            });

        modelBuilder.Entity("Chinese.Data.Word", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<int>("HashCode")
                    .HasColumnType("int");

                b.Property<string>("Simplified")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<string>("SimplifiedPinyin")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<string>("Traditional")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<string>("TraditionalPinyin")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Words");
            });
#pragma warning restore 612, 618
    }
}
