
namespace Chinese
{
    public static partial class Words
    {
        public static readonly ChineseWord[] NumericalWords = new[]
        {
            new ChineseWord { Pinyin = "yi1 she4", Simplified = "壹拾", Traditional = "壹拾", Tag = 10 },
            new ChineseWord { Pinyin = "er4 she4", Simplified = "贰拾", Traditional = "貳拾", Tag = 20 },
            new ChineseWord { Pinyin = "san1 she4", Simplified = "叁拾", Traditional = "叁拾", Tag = 30 },
            new ChineseWord { Pinyin = "si4 she4", Simplified = "肆拾", Traditional = "肆拾", Tag = 40 },
            new ChineseWord { Pinyin = "wu3 she4", Simplified = "伍拾", Traditional = "伍拾", Tag = 50 },
            new ChineseWord { Pinyin = "liu4 she4", Simplified = "陆拾", Traditional = "陸拾", Tag = 60 },
            new ChineseWord { Pinyin = "qi1 she4", Simplified = "柒拾", Traditional = "柒拾", Tag = 70 },
            new ChineseWord { Pinyin = "ba1 she4", Simplified = "捌拾", Traditional = "捌拾", Tag = 80 },
            new ChineseWord { Pinyin = "jiu3 she4", Simplified = "玖拾", Traditional = "玖拾", Tag = 90 },
            new ChineseWord { Pinyin = "yi1 bai3", Simplified = "壹佰", Traditional = "壹佰", Tag = 100 },
            new ChineseWord { Pinyin = "er4 bai3", Simplified = "贰佰", Traditional = "貳佰", Tag = 200 },
            new ChineseWord { Pinyin = "san1 bai3", Simplified = "叁佰", Traditional = "叁佰", Tag = 300 },
            new ChineseWord { Pinyin = "si4 bai3", Simplified = "肆佰", Traditional = "肆佰", Tag = 400 },
            new ChineseWord { Pinyin = "wu3 bai3", Simplified = "伍佰", Traditional = "伍佰", Tag = 500 },
            new ChineseWord { Pinyin = "liu4 bai3", Simplified = "陆佰", Traditional = "陸佰", Tag = 600 },
            new ChineseWord { Pinyin = "qi1 bai3", Simplified = "柒佰", Traditional = "柒佰", Tag = 700 },
            new ChineseWord { Pinyin = "ba1 bai3", Simplified = "捌佰", Traditional = "捌佰", Tag = 800 },
            new ChineseWord { Pinyin = "jiu3 bai3", Simplified = "玖佰", Traditional = "玖佰", Tag = 900 },
            new ChineseWord { Pinyin = "yi1 qian1", Simplified = "壹仟", Traditional = "壹仟", Tag = 1000 },
            new ChineseWord { Pinyin = "er4 qian1", Simplified = "贰仟", Traditional = "貳仟", Tag = 2000 },
            new ChineseWord { Pinyin = "san1 qian1", Simplified = "叁仟", Traditional = "叁仟", Tag = 3000 },
            new ChineseWord { Pinyin = "si4 qian1", Simplified = "肆仟", Traditional = "肆仟", Tag = 4000 },
            new ChineseWord { Pinyin = "wu3 qian1", Simplified = "伍仟", Traditional = "伍仟", Tag = 5000 },
            new ChineseWord { Pinyin = "liu4 qian1", Simplified = "陆仟", Traditional = "陸仟", Tag = 6000 },
            new ChineseWord { Pinyin = "qi1 qian1", Simplified = "柒仟", Traditional = "柒仟", Tag = 7000 },
            new ChineseWord { Pinyin = "ba1 qian1", Simplified = "捌仟", Traditional = "捌仟", Tag = 8000 },
            new ChineseWord { Pinyin = "jiu3 qian1", Simplified = "玖仟", Traditional = "玖仟", Tag = 9000 },
            new ChineseWord { Pinyin = "yi1", Simplified = "一", Traditional = "一", Tag = 1 },
            new ChineseWord { Pinyin = "er4", Simplified = "二", Traditional = "二", Tag = 2 },
            new ChineseWord { Pinyin = "san1", Simplified = "三", Traditional = "三", Tag = 3 },
            new ChineseWord { Pinyin = "si4", Simplified = "四", Traditional = "四", Tag = 4 },
            new ChineseWord { Pinyin = "wu3", Simplified = "五", Traditional = "五", Tag = 5 },
            new ChineseWord { Pinyin = "liu4", Simplified = "六", Traditional = "六", Tag = 6 },
            new ChineseWord { Pinyin = "qi1", Simplified = "七", Traditional = "七", Tag = 7 },
            new ChineseWord { Pinyin = "ba1", Simplified = "八", Traditional = "八", Tag = 8 },
            new ChineseWord { Pinyin = "jiu3", Simplified = "九", Traditional = "九", Tag = 9 },
            new ChineseWord { Pinyin = "yi1 shi2", Simplified = "一十", Traditional = "一十", Tag = 10 },
            new ChineseWord { Pinyin = "er4 shi2", Simplified = "二十", Traditional = "二十", Tag = 20 },
            new ChineseWord { Pinyin = "san1 shi2", Simplified = "三十", Traditional = "三十", Tag = 30 },
            new ChineseWord { Pinyin = "si4 shi2", Simplified = "四十", Traditional = "四十", Tag = 40 },
            new ChineseWord { Pinyin = "wu3 shi2", Simplified = "五十", Traditional = "五十", Tag = 50 },
            new ChineseWord { Pinyin = "liu4 shi2", Simplified = "六十", Traditional = "六十", Tag = 60 },
            new ChineseWord { Pinyin = "qi1 shi2", Simplified = "七十", Traditional = "七十", Tag = 70 },
            new ChineseWord { Pinyin = "ba1 shi2", Simplified = "八十", Traditional = "八十", Tag = 80 },
            new ChineseWord { Pinyin = "jiu3 shi2", Simplified = "九十", Traditional = "九十", Tag = 90 },
            new ChineseWord { Pinyin = "yi1 bai3", Simplified = "一百", Traditional = "一百", Tag = 100 },
            new ChineseWord { Pinyin = "er4 bai3", Simplified = "二百", Traditional = "二百", Tag = 200 },
            new ChineseWord { Pinyin = "san1 bai3", Simplified = "三百", Traditional = "三百", Tag = 300 },
            new ChineseWord { Pinyin = "si4 bai3", Simplified = "四百", Traditional = "四百", Tag = 400 },
            new ChineseWord { Pinyin = "wu3 bai3", Simplified = "五百", Traditional = "五百", Tag = 500 },
            new ChineseWord { Pinyin = "liu4 bai3", Simplified = "六百", Traditional = "六百", Tag = 600 },
            new ChineseWord { Pinyin = "qi1 bai3", Simplified = "七百", Traditional = "七百", Tag = 700 },
            new ChineseWord { Pinyin = "ba1 bai3", Simplified = "八百", Traditional = "八百", Tag = 800 },
            new ChineseWord { Pinyin = "jiu3 bai3", Simplified = "九百", Traditional = "九百", Tag = 900 },
            new ChineseWord { Pinyin = "yi1 qian1", Simplified = "一千", Traditional = "一千", Tag = 1000 },
            new ChineseWord { Pinyin = "er4 qian1", Simplified = "二千", Traditional = "二千", Tag = 2000 },
            new ChineseWord { Pinyin = "san1 qian1", Simplified = "三千", Traditional = "三千", Tag = 3000 },
            new ChineseWord { Pinyin = "si4 qian1", Simplified = "四千", Traditional = "四千", Tag = 4000 },
            new ChineseWord { Pinyin = "wu3 qian1", Simplified = "五千", Traditional = "五千", Tag = 5000 },
            new ChineseWord { Pinyin = "liu4 qian1", Simplified = "六千", Traditional = "六千", Tag = 6000 },
            new ChineseWord { Pinyin = "qi1 qian1", Simplified = "七千", Traditional = "七千", Tag = 7000 },
            new ChineseWord { Pinyin = "ba1 qian1", Simplified = "八千", Traditional = "八千", Tag = 8000 },
            new ChineseWord { Pinyin = "jiu3 qian1", Simplified = "九千", Traditional = "九千", Tag = 9000 },
        };

    }
}
