
namespace Chinese
{
    public static partial class Builtin
    {
        public static readonly ChineseWord[] NumericalWords = new[]
        {
            new ChineseWord { Simplified = "壹", Traditional = "壹", SimplifiedPinyin = "yi1", TraditionalPinyin = "yi1", Tag = 1 },
            new ChineseWord { Simplified = "贰", Traditional = "貳", SimplifiedPinyin = "er4", TraditionalPinyin = "er4", Tag = 2 },
            new ChineseWord { Simplified = "叁", Traditional = "叁", SimplifiedPinyin = "san1", TraditionalPinyin = "san1", Tag = 3 },
            new ChineseWord { Simplified = "肆", Traditional = "肆", SimplifiedPinyin = "si4", TraditionalPinyin = "si4", Tag = 4 },
            new ChineseWord { Simplified = "伍", Traditional = "伍", SimplifiedPinyin = "wu3", TraditionalPinyin = "wu3", Tag = 5 },
            new ChineseWord { Simplified = "陆", Traditional = "陸", SimplifiedPinyin = "lu4", TraditionalPinyin = "lu4", Tag = 6 },
            new ChineseWord { Simplified = "柒", Traditional = "柒", SimplifiedPinyin = "qi1", TraditionalPinyin = "qi1", Tag = 7 },
            new ChineseWord { Simplified = "捌", Traditional = "捌", SimplifiedPinyin = "ba1", TraditionalPinyin = "ba1", Tag = 8 },
            new ChineseWord { Simplified = "玖", Traditional = "玖", SimplifiedPinyin = "jiu3", TraditionalPinyin = "jiu3", Tag = 9 },
            new ChineseWord { Simplified = "壹拾", Traditional = "壹拾", SimplifiedPinyin = "yi1 shi2", TraditionalPinyin = "yi1 shi2", Tag = 10 },
            new ChineseWord { Simplified = "贰拾", Traditional = "貳拾", SimplifiedPinyin = "er4 shi2", TraditionalPinyin = "er4 shi2", Tag = 20 },
            new ChineseWord { Simplified = "叁拾", Traditional = "叁拾", SimplifiedPinyin = "san1 shi2", TraditionalPinyin = "san1 shi2", Tag = 30 },
            new ChineseWord { Simplified = "肆拾", Traditional = "肆拾", SimplifiedPinyin = "si4 shi2", TraditionalPinyin = "si4 shi2", Tag = 40 },
            new ChineseWord { Simplified = "伍拾", Traditional = "伍拾", SimplifiedPinyin = "wu3 shi2", TraditionalPinyin = "wu3 shi2", Tag = 50 },
            new ChineseWord { Simplified = "陆拾", Traditional = "陸拾", SimplifiedPinyin = "lu4 shi2", TraditionalPinyin = "lu4 shi2", Tag = 60 },
            new ChineseWord { Simplified = "柒拾", Traditional = "柒拾", SimplifiedPinyin = "qi1 shi2", TraditionalPinyin = "qi1 shi2", Tag = 70 },
            new ChineseWord { Simplified = "捌拾", Traditional = "捌拾", SimplifiedPinyin = "ba1 shi2", TraditionalPinyin = "ba1 shi2", Tag = 80 },
            new ChineseWord { Simplified = "玖拾", Traditional = "玖拾", SimplifiedPinyin = "jiu3 shi2", TraditionalPinyin = "jiu3 shi2", Tag = 90 },
            new ChineseWord { Simplified = "壹佰", Traditional = "壹佰", SimplifiedPinyin = "yi1 bai3", TraditionalPinyin = "yi1 bai3", Tag = 100 },
            new ChineseWord { Simplified = "贰佰", Traditional = "貳佰", SimplifiedPinyin = "er4 bai3", TraditionalPinyin = "er4 bai3", Tag = 200 },
            new ChineseWord { Simplified = "叁佰", Traditional = "叁佰", SimplifiedPinyin = "san1 bai3", TraditionalPinyin = "san1 bai3", Tag = 300 },
            new ChineseWord { Simplified = "肆佰", Traditional = "肆佰", SimplifiedPinyin = "si4 bai3", TraditionalPinyin = "si4 bai3", Tag = 400 },
            new ChineseWord { Simplified = "伍佰", Traditional = "伍佰", SimplifiedPinyin = "wu3 bai3", TraditionalPinyin = "wu3 bai3", Tag = 500 },
            new ChineseWord { Simplified = "陆佰", Traditional = "陸佰", SimplifiedPinyin = "lu4 bai3", TraditionalPinyin = "lu4 bai3", Tag = 600 },
            new ChineseWord { Simplified = "柒佰", Traditional = "柒佰", SimplifiedPinyin = "qi1 bai3", TraditionalPinyin = "qi1 bai3", Tag = 700 },
            new ChineseWord { Simplified = "捌佰", Traditional = "捌佰", SimplifiedPinyin = "ba1 bai3", TraditionalPinyin = "ba1 bai3", Tag = 800 },
            new ChineseWord { Simplified = "玖佰", Traditional = "玖佰", SimplifiedPinyin = "jiu3 bai3", TraditionalPinyin = "jiu3 bai3", Tag = 900 },
            new ChineseWord { Simplified = "壹仟", Traditional = "壹仟", SimplifiedPinyin = "yi1 qian1", TraditionalPinyin = "yi1 qian1", Tag = 1000 },
            new ChineseWord { Simplified = "贰仟", Traditional = "貳仟", SimplifiedPinyin = "er4 qian1", TraditionalPinyin = "er4 qian1", Tag = 2000 },
            new ChineseWord { Simplified = "叁仟", Traditional = "叁仟", SimplifiedPinyin = "san1 qian1", TraditionalPinyin = "san1 qian1", Tag = 3000 },
            new ChineseWord { Simplified = "肆仟", Traditional = "肆仟", SimplifiedPinyin = "si4 qian1", TraditionalPinyin = "si4 qian1", Tag = 4000 },
            new ChineseWord { Simplified = "伍仟", Traditional = "伍仟", SimplifiedPinyin = "wu3 qian1", TraditionalPinyin = "wu3 qian1", Tag = 5000 },
            new ChineseWord { Simplified = "陆仟", Traditional = "陸仟", SimplifiedPinyin = "lu4 qian1", TraditionalPinyin = "lu4 qian1", Tag = 6000 },
            new ChineseWord { Simplified = "柒仟", Traditional = "柒仟", SimplifiedPinyin = "qi1 qian1", TraditionalPinyin = "qi1 qian1", Tag = 7000 },
            new ChineseWord { Simplified = "捌仟", Traditional = "捌仟", SimplifiedPinyin = "ba1 qian1", TraditionalPinyin = "ba1 qian1", Tag = 8000 },
            new ChineseWord { Simplified = "玖仟", Traditional = "玖仟", SimplifiedPinyin = "jiu3 qian1", TraditionalPinyin = "jiu3 qian1", Tag = 9000 },
            new ChineseWord { Simplified = "一", Traditional = "一", SimplifiedPinyin = "yi1", TraditionalPinyin = "yi1", Tag = 1 },
            new ChineseWord { Simplified = "二", Traditional = "二", SimplifiedPinyin = "er4", TraditionalPinyin = "er4", Tag = 2 },
            new ChineseWord { Simplified = "三", Traditional = "三", SimplifiedPinyin = "san1", TraditionalPinyin = "san1", Tag = 3 },
            new ChineseWord { Simplified = "四", Traditional = "四", SimplifiedPinyin = "si4", TraditionalPinyin = "si4", Tag = 4 },
            new ChineseWord { Simplified = "五", Traditional = "五", SimplifiedPinyin = "wu3", TraditionalPinyin = "wu3", Tag = 5 },
            new ChineseWord { Simplified = "六", Traditional = "六", SimplifiedPinyin = "liu4", TraditionalPinyin = "liu4", Tag = 6 },
            new ChineseWord { Simplified = "七", Traditional = "七", SimplifiedPinyin = "qi1", TraditionalPinyin = "qi1", Tag = 7 },
            new ChineseWord { Simplified = "八", Traditional = "八", SimplifiedPinyin = "ba1", TraditionalPinyin = "ba1", Tag = 8 },
            new ChineseWord { Simplified = "九", Traditional = "九", SimplifiedPinyin = "jiu3", TraditionalPinyin = "jiu3", Tag = 9 },
            new ChineseWord { Simplified = "一十", Traditional = "一十", SimplifiedPinyin = "yi1 shi2", TraditionalPinyin = "yi1 shi2", Tag = 10 },
            new ChineseWord { Simplified = "二十", Traditional = "二十", SimplifiedPinyin = "er4 shi2", TraditionalPinyin = "er4 shi2", Tag = 20 },
            new ChineseWord { Simplified = "三十", Traditional = "三十", SimplifiedPinyin = "san1 shi2", TraditionalPinyin = "san1 shi2", Tag = 30 },
            new ChineseWord { Simplified = "四十", Traditional = "四十", SimplifiedPinyin = "si4 shi2", TraditionalPinyin = "si4 shi2", Tag = 40 },
            new ChineseWord { Simplified = "五十", Traditional = "五十", SimplifiedPinyin = "wu3 shi2", TraditionalPinyin = "wu3 shi2", Tag = 50 },
            new ChineseWord { Simplified = "六十", Traditional = "六十", SimplifiedPinyin = "liu4 shi2", TraditionalPinyin = "liu4 shi2", Tag = 60 },
            new ChineseWord { Simplified = "七十", Traditional = "七十", SimplifiedPinyin = "qi1 shi2", TraditionalPinyin = "qi1 shi2", Tag = 70 },
            new ChineseWord { Simplified = "八十", Traditional = "八十", SimplifiedPinyin = "ba1 shi2", TraditionalPinyin = "ba1 shi2", Tag = 80 },
            new ChineseWord { Simplified = "九十", Traditional = "九十", SimplifiedPinyin = "jiu3 shi2", TraditionalPinyin = "jiu3 shi2", Tag = 90 },
            new ChineseWord { Simplified = "一百", Traditional = "一百", SimplifiedPinyin = "yi1 bai3", TraditionalPinyin = "yi1 bai3", Tag = 100 },
            new ChineseWord { Simplified = "二百", Traditional = "二百", SimplifiedPinyin = "er4 bai3", TraditionalPinyin = "er4 bai3", Tag = 200 },
            new ChineseWord { Simplified = "三百", Traditional = "三百", SimplifiedPinyin = "san1 bai3", TraditionalPinyin = "san1 bai3", Tag = 300 },
            new ChineseWord { Simplified = "四百", Traditional = "四百", SimplifiedPinyin = "si4 bai3", TraditionalPinyin = "si4 bai3", Tag = 400 },
            new ChineseWord { Simplified = "五百", Traditional = "五百", SimplifiedPinyin = "wu3 bai3", TraditionalPinyin = "wu3 bai3", Tag = 500 },
            new ChineseWord { Simplified = "六百", Traditional = "六百", SimplifiedPinyin = "liu4 bai3", TraditionalPinyin = "liu4 bai3", Tag = 600 },
            new ChineseWord { Simplified = "七百", Traditional = "七百", SimplifiedPinyin = "qi1 bai3", TraditionalPinyin = "qi1 bai3", Tag = 700 },
            new ChineseWord { Simplified = "八百", Traditional = "八百", SimplifiedPinyin = "ba1 bai3", TraditionalPinyin = "ba1 bai3", Tag = 800 },
            new ChineseWord { Simplified = "九百", Traditional = "九百", SimplifiedPinyin = "jiu3 bai3", TraditionalPinyin = "jiu3 bai3", Tag = 900 },
            new ChineseWord { Simplified = "一千", Traditional = "一千", SimplifiedPinyin = "yi1 qian1", TraditionalPinyin = "yi1 qian1", Tag = 1000 },
            new ChineseWord { Simplified = "二千", Traditional = "二千", SimplifiedPinyin = "er4 qian1", TraditionalPinyin = "er4 qian1", Tag = 2000 },
            new ChineseWord { Simplified = "三千", Traditional = "三千", SimplifiedPinyin = "san1 qian1", TraditionalPinyin = "san1 qian1", Tag = 3000 },
            new ChineseWord { Simplified = "四千", Traditional = "四千", SimplifiedPinyin = "si4 qian1", TraditionalPinyin = "si4 qian1", Tag = 4000 },
            new ChineseWord { Simplified = "五千", Traditional = "五千", SimplifiedPinyin = "wu3 qian1", TraditionalPinyin = "wu3 qian1", Tag = 5000 },
            new ChineseWord { Simplified = "六千", Traditional = "六千", SimplifiedPinyin = "liu4 qian1", TraditionalPinyin = "liu4 qian1", Tag = 6000 },
            new ChineseWord { Simplified = "七千", Traditional = "七千", SimplifiedPinyin = "qi1 qian1", TraditionalPinyin = "qi1 qian1", Tag = 7000 },
            new ChineseWord { Simplified = "八千", Traditional = "八千", SimplifiedPinyin = "ba1 qian1", TraditionalPinyin = "ba1 qian1", Tag = 8000 },
            new ChineseWord { Simplified = "九千", Traditional = "九千", SimplifiedPinyin = "jiu3 qian1", TraditionalPinyin = "jiu3 qian1", Tag = 9000 },
            new ChineseWord { Simplified = "两", Traditional = "两", SimplifiedPinyin = "liang3", TraditionalPinyin = "liang3", Tag = 2 },
            new ChineseWord { Simplified = "两百", Traditional = "两百", SimplifiedPinyin = "liang3 bai3", TraditionalPinyin = "liang3 bai3", Tag = 200 },
            new ChineseWord { Simplified = "两千", Traditional = "两千", SimplifiedPinyin = "liang3 qian1", TraditionalPinyin = "liang3 qian1", Tag = 2000 },
            // Total 75 words.
        };

    }
}
